---

name: SiamMask
gops: 37.566

time: true

model: $(home)/SiamMask_DAVIS_trace.pt
input_shapes: "[1,3,127,127],[1,3,255,255]"
batch_sizes: [1]

int8_model: $(workdir)/$(name)_bmnetp_deploy_int8_unique_top.prototxt
int8_weight: $(workdir)/$(name)_bmnetp.int8umodel

BM1684X:
  fp_loops:
    - build_env: [  ]
      opt: "1"
      dyn: "False"
      fp_outdir_template: "static.opt1.fp32.{}b.compilation"
      prec: FP32
    - build_env: [  ]
      opt: "2"
      dyn: "True"
      fp_outdir_template: "dynamic.opt2.fp32.{}b.compilation"
      prec: FP32
    - build_env:
        - BMCOMPILER_LAYER_DTYPE_MODE=auto
      opt: "1"
      dyn: "False"
      fp_outdir_template: "static.opt1.fp16.{}b.compilation"
      prec: FP16
    - build_env:
        - BMCOMPILER_LAYER_DTYPE_MODE=auto
      opt: "2"
      dyn: "True"
      fp_outdir_template: "dynamic.opt2.fp16.{}b.compilation"
      prec: FP16

  int8_loops:
    - opt: "1"
      dyn: "False"
      int8_outdir_template: "static.opt1.int8.{}b.compilation"
    - opt: "2"
      dyn: "True"
      int8_outdir_template: "dynamic.opt2.int8.{}b.compilation"

  fp_batch_sizes: $(batch_sizes)
  fp_compile_options:
    python3 -m bmnetp
      --model $(model)
      --shapes $(input_shapes)
      --net_name $(name)
      --target $(target)
      --enable_profile True

  time_only_cali:
    python3 -m ufw.cali.cali_model
      --model $(model)
      --input_shapes "[1,3,127,127];[1,3,255,255]"
      --net_name $(name)
      --cali_iteration 1
      --target $(target)
      --test_iterations 1
      --debug_cmd "not_call_bmnetu;not_suspend;use_fake_data_to_test"

  bmnetu_batch_sizes: $(batch_sizes)
  bmnetu_options:
    --model $(int8_model)
    --weight $(int8_weight)
    --target $(target)
    --enable_profile True
