---

name: res2net50_26w_4s
gops: 8.570381272

model: $(home)/res2net50_26w_4s.onnx
batch_sizes: [1]

BM1684X:
  fp_loops:
    - build_env: [  ]
      fp_outdir_template: "{}b.fp32.compilation"
      prec: FP32
    - build_env:
        - BMCOMPILER_LAYER_DTYPE_MODE=auto
      fp_outdir_template: "{}b.fp16.compilation"
      prec: FP16

  fp_batch_sizes: $(batch_sizes)

  fp_compile_options:
    python3 -m bmneto
    --model $(model)
    --net_name $(name)
    --shapes [1,3,224,224]
    --target BM1684X
    --enable_profile True
