---

name: opus-mt-zh-en-init-decoder
gops: 0.118300166

model: $(home)/opus-mt-zh-en-init-decoder.onnx

time: true
runtime_cmp: false

BM1684X:
  fp_compile_options:
    python3 -m bmneto
    --model $(model)
    --shapes [[1,1],[1,1,512]]
    --target $(target)
    --enable_profile True
    --opt 1
    --dyn True
    --cmp 0
    --descs "[0,int64,0,65001],[1,float32,0,1]"
