---

name: solov2_r50_1x

gops: [7.766]

shapes:
  - [[1, 3, 448, 448], [1, 2, 56, 56], [1, 2, 28, 28], [1, 2, 14, 14]]

precision: false

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(home)/solov2_r50_1x.onnx
    --input_shapes [$(shape_param)]
    --mean 123.675,116.28,103.53
    --scale 0.01712475,0.01750700,0.01742919
    --test_input $(home)/input.npz
    --test_result $(name)_top_outputs.npz
    --pixel_format rgb
    --mlir $(workdir)/transformed.mlir

# mlir_calibration:
#   run_calibration.py $(workdir)/transformed.mlir
#     --dataset $(home)
#     --input_num 1
#     -o $(home)/cali_table

#   run_qtable.py $(workdir)/transformed.mlir
#     --dataset $(home)
#     --calibration_table $(workdir)/cali_table
#     --min_layer_cos 0.99
#     --chip bm1684x
#     --expected_cos 0.999
#     -o $(home)/q_table
BM1684X:
  deploy:
    - model_deploy.py  --mlir $(workdir)/transformed.mlir
        --quantize F32
        --chip $(target)
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.99,0.99
        --model $(workdir)/$(name)_bm1684x_f32.bmodel
    - model_deploy.py --mlir $(workdir)/transformed.mlir
        --quantize INT8
        --calibration_table $(home)/cali_table
        --quantize_table $(home)/q_table
        --chip $(target)
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.68,0.10
        --model $(workdir)/$(name)_bm1684x_int8_sym.bmodel
    - model_deploy.py --mlir $(workdir)/transformed.mlir
        --quantize INT8
        --asymmetric
        --calibration_table $(home)/cali_table
        --quantize_table $(home)/q_table
        --chip $(target)
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.60,0.10
        --model $(workdir)/$(name)_bm1684x_int8_asym.bmodel
