---

name: resnet34-v1-7
gops: 7.345687528

model: $(home)/resnet34-v1-7.onnx

time: true
precision: false

fp_batch_sizes: [1, 2, 4, 8]

fp_compile_options:
  python3 -m bmneto
  --model $(model)
  --shapes [1,3,224,224]
  --target $(target)
  --enable_profile True
  --opt 1
  --cmp 1

time_only_cali:
  python3 -m ufw.cali.cali_model
    --model $(model)
    --test_iterations 1
    --net_name $(name)
    --postprocess_and_calc_score_class none
    --debug_cmd="not_call_bmnetu;not_suspend;use_fake_data_to_test"
    --target=$(target)
    --cali_iterations 1
    --input_shapes=[1,3,224,224]

int8_model: $(workdir)/$(name)_bmneto_deploy_int8_unique_top.prototxt
int8_weight: $(workdir)/$(name)_bmneto.int8umodel
bmnetu_batch_sizes: [1, 4, 8, 16]
bmnetu_options:
  --opt=2
  --cmp=True
  --target $(target)
  --model $(int8_model)
  --weight $(int8_weight)
  --seed 42
  --enable_profile=True
