---

name: mtcnn_pnet
gops: 0.000095

model: $(home)/det1.prototxt
weight: $(home)/det1.caffemodel
int8_model: $(workdir)/$(name)_bmnetc_deploy_int8_unique_top.prototxt
int8_weight: $(workdir)/$(name)_bmnetc.int8umodel

fp_compile_options:
  bmnetc
  --model $(model)
  --weight $(weight)
  --shapes [1,3,12,12]
  --target $(target)
  --opt 1
  --cmp 1

time_only_cali:
  python3 -m ufw.cali.cali_model
    --model $(model)
    --weights $(weight)
    --test_iterations 1
    --net_name $(name)
    --postprocess_and_calc_score_class none
    --debug_cmd='use_fake_data_to_test;not_call_bmnetu'
    --target=$(target)
    --cali_iterations 1
    --input_shapes=[1,3,12,12]

bmnetu_options:
  --opt=2
  --cmp=True
  --target $(target)
  --model $(int8_model)
  --weight $(int8_weight)
  --seed 42
  --enable_profile=True

bmnetu_batch_sizes: [1, 4, 8, 16]

shapes:
  - [1, 3, 12, 12]

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(home)/det1.prototxt
    --model_data $(home)/det1.caffemodel
    --test_input $(root)/dataset/samples/stock_market.jpg
    --input_shapes [$(shape_param)]
    --test_result $(name)_top_outputs.npz
    --mlir $(workdir)/transformed.mlir

deploy:
  - model_deploy.py  --mlir $(workdir)/transformed.mlir
      --quantize F32
      --chip bm1684x
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.99,0.99
      --model $(workdir)/$(name)_bm1684x_f32.bmodel
  - model_deploy.py --mlir $(workdir)/transformed.mlir
      --quantize F16
      --chip bm1684x
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.95,0.85
      --model $(workdir)/$(name)_bm1684x_f16.bmodel
  - model_deploy.py --mlir $(workdir)/transformed.mlir
      --quantize BF16
      --chip bm1684x
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.95,0.85
      --model $(workdir)/$(name)_bm1684x_bf16.bmodel
  - model_deploy.py --mlir $(workdir)/transformed.mlir
      --quantize INT8
      --calibration_table $(home)/det1_cali_table
      --quant_input
      --quant_output
      --chip bm1684x
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.88,0.26
      --model $(workdir)/$(name)_bm1684x_int8_sym.bmodel
