---

name: inception_resnet_v2
gops: 30.624

fp_batch_sizes: [1, 4, 8, 16]

model: $(home)/deploy_inception-resnet-v2.prototxt
weight: $(home)/inception-resnet-v2.caffemodel
int8_model: $(workdir)/$(name)_bmnetc_deploy_int8_unique_top.prototxt
int8_weight: $(workdir)/$(name)_bmnetc.int8umodel

BM1684:
  fp_loops:
    - build_env:
        - BMCOMPILER_GROUP_SEARCH_COUNT=1
      opt: "1"
      dyn: "False"
      fp_outdir_template: "static.opt1.fp32.{}b.compilation"
      prec: FP32
    - build_env:
        - BMCOMPILER_GROUP_SEARCH_COUNT=1
      opt: "2"
      dyn: "True"
      fp_outdir_template: "dynamic.opt2.fp32.{}b.compilation"
      prec: FP32

BM1684X:
  fp_loops:
    - build_env:
        - BMCOMPILER_GROUP_SEARCH_COUNT=1
      opt: "1"
      dyn: "False"
      fp_outdir_template: "static.opt1.fp32.{}b.compilation"
      prec: FP32
    - build_env:
        - BMCOMPILER_GROUP_SEARCH_COUNT=1
      opt: "2"
      dyn: "True"
      fp_outdir_template: "dynamic.opt2.fp32.{}b.compilation"
      prec: FP32
    - build_env:
        - BMCOMPILER_LAYER_DTYPE_MODE=auto
        - BMCOMPILER_GROUP_SEARCH_COUNT=1
      opt: "1"
      dyn: "False"
      fp_outdir_template: "static.opt1.fp16.{}b.compilation"
      prec: FP16
    - build_env:
        - BMCOMPILER_LAYER_DTYPE_MODE=auto
        - BMCOMPILER_GROUP_SEARCH_COUNT=1
      opt: "2"
      dyn: "True"
      fp_outdir_template: "dynamic.opt2.fp16.{}b.compilation"
      prec: FP16

int8_loops:
  - build_env:
      - BMCOMPILER_GROUP_SEARCH_COUNT=1
    opt: "1"
    dyn: "False"
    int8_outdir_template: "static.opt1.int8.{}b.compilation"
  - build_env:
      - BMCOMPILER_GROUP_SEARCH_COUNT=1
    opt: "2"
    dyn: "True"
    int8_outdir_template: "dynamic.opt2.int8.{}b.compilation"

fp_compile_options:
  bmnetc
    --model $(model)
    --weight $(weight)
    --shapes [1,3,229,229]
    --net_name $(name)
    --target $(target)
    --enable_profile true
    --cmp false

time_only_cali:
  python3 -m ufw.cali.cali_model
    --model $(model)
    --weights $(weight)
    --input_shapes "[1,3,229,229]"
    --net_name $(name)
    --test_iterations 1
    --target $(target)
    --cali_iterations 1
    --debug_cmd "use_fake_data_to_test;not_suspend;not_call_bmnetu"

bmnetu_options:
  --target $(target)
  --model $(int8_model)
  --weight $(int8_weight)
  --seed 42
  --enable_profile=True

bmnetu_batch_sizes: [1, 4, 8, 16]
