---

name: openpose
gops: 98.7

model: $(home)/pose_deploy.prototxt
weight: $(home)/pose_iter_584000.caffemodel
int8_model: $(workdir)/$(name)_bmnetc_deploy_int8_unique_top.prototxt
int8_weight: $(workdir)/$(name)_bmnetc.int8umodel

fp_compile_options:
  bmnetc
  --model $(model)
  --weight $(weight)
  --shapes [1,3,216,384]
  --target $(target)
  --enable_profile true
  --opt 1
  --cmp 1

time_only_cali:
  python3 -m ufw.cali.cali_model
    --model $(model)
    --weights $(weight)
    --test_iterations 1
    --net_name $(name)
    --postprocess_and_calc_score_class none
    --debug_cmd='use_fake_data_to_test;not_call_bmnetu;not_suspend'
    --target=$(target)
    --cali_iterations 1
    --input_shapes=[1,3,216,384]

bmnetu_options:
  --opt=1
  --cmp=True
  --target $(target)
  --model $(int8_model)
  --weight $(int8_weight)
  --seed 42
  --enable_profile=True

bmnetu_batch_sizes: [1, 4, 8, 16]

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(home)/pose_deploy.prototxt
    --model_data $(home)/pose_iter_584000.caffemodel
    --test_input $(root)/dataset/samples/reid_img.jpg
    --input_shapes [[1,3,216,384]]
    --test_result $(name)_top_outputs.npz
    --mlir $(workdir)/transformed.mlir

deploy:
  - model_deploy.py  --mlir $(workdir)/transformed.mlir
      --quantize F32
      --chip bm1684x
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.99,0.99
      --model $(workdir)/$(name)_bm1684x_f32.bmodel
  - model_deploy.py --mlir $(workdir)/transformed.mlir
      --quantize INT8
      --calibration_table $(home)/cali_table
      --quant_input
      --quant_output
      --asymmetric
      --chip bm1684x
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.69,0.14
      --model $(workdir)/$(name)_bm1684x_int8_asym.bmodel
