---

name: res2net101_26w_4s

gops: [16.221452952]

shapes:
  - [1, 3, 224, 224]

model: $(home)/res2net101_26w_4s.onnx

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(home)/res2net101_26w_4s.onnx
    --input_shapes [[1,3,224,224]]
    --mean 0,0,0
    --scale 0.0039216,0.0039216,0.0039216
    --test_input $(root)/dataset/samples/Cat.jpg
    --test_result $(name)_top_outputs.npz
    --pixel_format rgb
    --mlir $(workdir)/transformed.mlir

mlir_calibration:
  run_calibration.py $(workdir)/transformed.mlir
    --dataset $(coco2017_mlir_cali_set)
    --input_num 100
    -o $(home)/cali_table

deploy:
  - model_deploy.py  --mlir $(workdir)/transformed.mlir
      --quantize F32
      --chip bm1684x
      --tolerance 0.99,0.99
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --model $(workdir)/$(name)_bm1684x_f32.bmodel
  - model_deploy.py --mlir $(workdir)/transformed.mlir
      --quantize INT8
      --calibration_table $(home)/cali_table
      --chip bm1684x
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.98,0.78
      --model $(workdir)/$(name)_bm1684x_int8_sym.bmodel
  - model_deploy.py --mlir $(workdir)/transformed.mlir
      --quantize INT8
      --asymmetric
      --calibration_table $(home)/cali_table
      --chip bm1684x
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.98,0.82
      --model $(workdir)/$(name)_bm1684x_int8_asym.bmodel